### ISSUE TITLE
Aaa

### ISSUE THREAD

**Issue by xeton** [blazeroleplay/kozosseg#3]
Jelentkezési lap

Bemutatkozás (5-10 mondatban)aaaa
~ Válasz ~

Mennyi perccel rendelkezel jelenleg a szerveren?
~ Válasz ~

Mi az Adminsegéd feladata?
~ Válasz ~

Miért szeretnél Adminsegéd lenni?
~ Válasz ~

Miért pont téged válasszunk?
~ Válasz ~

Milyen szintű lenne az aktivitásod Adminsegédként a szerveren?
~ Válasz ~

Írj 3-3db negatív és pozitív tulajdonságot magadról.
~ Válasz ~

Szeretnél a későbbiekben adminisztrátor lenni? Ha igen miért? (minimum 5 mondat)
~ Válasz ~
​
Ez csak egy minta a kötelezőkről. A design teljesen rád van bízva, légy kreatív.

**Comment by blazeroleplay** [comment]
asd
